name: Upload and Download Artifacts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create a file to upload
        run: echo "Hello from build job!" > message.txt

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: example-artifact
          path: message.txt

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: example-artifact

      - name: Show downloaded file
        run: cat message.txt
