name: cutom-environment-variables

on: push

# Workflow-level environment variable
env:
  WORKFLOW_VAR: variable_from_workflow

jobs:
  example-job:
    runs-on: ubuntu-latest

    # Job-level environment variable
    env:
      JOB_VAR: variable_from_job

    steps:
      - name: Echo all levels (workflow + job only)
        run: |
          echo "WORKFLOW_VAR: $WORKFLOW_VAR"
          echo "JOB_VAR: $JOB_VAR"
          echo "STEP_VAR: $STEP_VAR (should be empty)"

      - name: Echo with step-level variable
        run: |
          echo "WORKFLOW_VAR: $WORKFLOW_VAR"
          echo "JOB_VAR: $JOB_VAR"
          echo "STEP_VAR: $STEP_VAR"
        env:
          STEP_VAR: variable_from_step
