# .github/workflows/use-ci.yml
name: Run CI via Reusable Workflow

on:
  push:

jobs:
  test:
    uses: kworaitthinan-avanade/github-action-demo/.github/workflows/ci-pipeline-reusable-workflow.yml@main
    with:
      node-version: "16"
    secrets: # Or user secrets: inherit to pass all secrets.
      npm-token: ${{ secrets.NPM_TOKEN }}
