name: Python Build (Docker)

on:
  push:
    branches:
      - main

env:
  DEPENDENCY_FILE: requirements.txt

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: python:3.8

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.DEPENDENCY_FILE }}
