name: Test DB Schema Build

on: [push, pull_request]

jobs:
  db-schema-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U testuser; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 2
          done

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Run init_schema.sql
        run: |
          psql -h localhost -U testuser -d testdb -f db/init_schema.sql
        env:
          PGPASSWORD: testpass

      - name: Check schema
        run: |
          psql -h localhost -U testuser -d testdb -f db/check_schema.sql
        env:
          PGPASSWORD: testpass
