name: Reusable CI Pipeline
on: push
jobs:
  test:
    uses: kworaitthinan-avanade/github-action-demo/.github/workflows/ci-pipeline-reusable-workflow.yml@v1
    with:
      node-version: "16"
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
