name: Test A - Use Job Outputs for Secrets

on: [push]

env:
  EXPECTED_SECRET_VALUE: run-job

jobs:
  expose-secret:
    runs-on: ubuntu-latest
    outputs:
      mysecret: ${{ steps.set-secret.outputs.secret }}
    steps:
      - id: set-secret
        run: |
          echo "secret=${{ env.EXPECTED_SECRET_VALUE }}" >> $GITHUB_OUTPUT

  dependent-job:
    needs: expose-secret
    runs-on: ubuntu-latest
    if: needs.expose-secret.outputs.mysecret == 'run-job'
    steps:
      - run: |
          echo "A PASSED: Used job output for secret successfully."
