name: Test B - Set Env and Try in Job If

on: [push]

env:
  EXPECTED_SECRET_VALUE: run-job

jobs:
  env-test-job:
    runs-on: ubuntu-latest
    env:
      MY_SECRET: ${{ env.EXPECTED_SECRET_VALUE }}
    if: env.MY_SECRET == 'run-job'
    steps:
      - run: |
          echo "B PASSED: Env variable worked in job if."
