name: Test C - Use Step Outputs for Secrets

on: [push]

env:
  EXPECTED_SECRET_VALUE: run-job

jobs:
  expose-step-output:
    runs-on: ubuntu-latest
    outputs:
      stepsecret: ${{ steps.set-output.outputs.secret }}
    steps:
      - id: set-output
        run: |
          echo "secret=${{ env.EXPECTED_SECRET_VALUE }}" >> $GITHUB_OUTPUT

  use-step-output:
    needs: expose-step-output
    runs-on: ubuntu-latest
    if: needs.expose-step-output.outputs.stepsecret == 'run-job'
    steps:
      - run: |
          echo "C PASSED: Step output for secret used successfully."
