name: Test D - Use Secrets Directly in Job If

on: [push]

jobs:
  direct-secrets-if:
    runs-on: ubuntu-latest
    if: secrets.MY_SECRET == 'run-job'
    steps:
      - run: |
          echo "D PASSED: Used secrets directly."
