# .github/workflows/conditional-workflow.yml
name: Conditional Workflow

on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests only on non-main branches
        if: github.ref != 'refs/heads/main' # using ${{ }} implicitly
        run: echo "Running tests because this is NOT the main branch."

  build-or-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # using ${{ }} implicitly
    steps:
      - name: Echo environment
        run: |
          echo "This is the main branch, prepare to deploy."

      - name: Simulate conditional shell logic without expression
        run: |
          BRANCH=$(echo "${GITHUB_REF##*/}")
          if [ "$BRANCH" = "main" ]; then
            echo "Deploying to production..."
          else
            echo "Skipping deploy"
          fi
