name: Manual Dispatch

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run a sample script
        run: echo "Log level is ${{ github.event.inputs.logLevel }} and tags are ${{ github.event.inputs.tags }}"
