name: print-environment-variables
on: push

jobs:
  prod-check:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Print environment variables
        run: |
          echo "GITHUB_REF = $GITHUB_REF"
          echo "GITHUB_SHA = $GITHUB_SHA"
          echo "GITHUB_REPOSITORY = $GITHUB_REPOSITORY"
          echo "GITHUB_ACTOR = $GITHUB_ACTOR"
          echo "GITHUB_WORKFLOW = $GITHUB_WORKFLOW"
          echo "GITHUB_HEAD_REF = $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF = $GITHUB_BASE_REF"
          echo "GITHUB_EVENT_NAME = $GITHUB_EVENT_NAME"
          echo "GITHUB_RUN_NUMBER = $GITHUB_RUN_NUMBER"
          echo "GITHUB_RUN_ID = $GITHUB_RUN_ID"
          echo "GITHUB_JOB = $GITHUB_JOB"
          echo "GITHUB_ACTION = $GITHUB_ACTION"
          echo "GITHUB_EVENT_PATH = $GITHUB_EVENT_PATH"
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          echo "HOME = $HOME"
          echo "RUNNER_OS = $RUNNER_OS"
          echo "RUNNER_NAME = $RUNNER_NAME"
          echo "RUNNER_ARCH = $RUNNER_ARCH"

      - name: Print all environment variables
        run: printenv
