name: Run External Build Script

on: push

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make build script executable
        run: chmod +x .github/scripts/build.sh

      - name: Run build script
        run: ./.github/scripts/build.sh
