name: Secrets and Variables

on:
  push:
  workflow_dispatch:

jobs:
  use-secrets-and-vars:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Access environment variable
        run: |
          echo "MY_VARIABLE_NAME: $MY_VARIABLE_NAME"
        env:
          MY_VARIABLE_NAME: ${{ vars.MY_VARIABLE_NAME }}

      - name: Access secret (safely)
        run: echo "Secret is set!"
        env:
          SECRET_VALUE: ${{ secrets.MY_SECRET_TOKEN }}

      - name: Use both in a script
        run: |
          echo "Running in $MY_ENVIRONMENT environment"
          echo "Using secret token of length: ${#SECRET_VALUE}"
        env:
          MY_ENVIRONMENT: ${{ vars.MY_VARIABLE_NAME }}
          SECRET_VALUE: ${{ secrets.MY_SECRET_TOKEN }}
